### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by chriscalo** [reframejs/goldpage#11]
It looks like `*.page.js` files choke when trying to resolve core node modules.

Here's a simple page config file that grabs the contents of a SQL file and makes a simple database query:

``` js
import { file } from "ez-file";
import { query } from "~/util/db";
import page from "./index.vue";

export default {
  route: "/vars/",
  view: page,
  renderToHtml: true,
  async addInitialProps({ res: { req }, res, next }) {
    const sql = file("./vars.sql");
    const [ vars ] = await query(sql);
    
    return {
      vars: {
        ...vars,
        timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      },
    };
  },
};
```

This seems to build successfully, but when visiting this page, I get the following error:

``` text
ERROR in ./node_modules/ez-file/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/chriscalo/Projects/viaticus/node_modules/ez-file'
resolve 'fs' in '/Users/chriscalo/Projects/viaticus/node_modules/ez-file'
```

My guess is that webpack isn't configured to resolve core node modules, but I don't have experience using webapck to build for Node.js execution.

**Comment by brillout** [comment]
Yes exactly, webpack tries to build `fs`.

A trick to bypass webpack is to use eval:

~~~js
import assert from '@brillout/assert';

export default {
  route: "/vars/",
  view: page,
  renderToHtml: true,
  async addInitialProps({ res: { req }, res, next }) {

    // Make sure that addInitialProps is always only called in Node.js
    assert.internal(isNodejs());

    // The `~/database/query` module will not be built by webpack.
    // Instead, Node.js's `require` will directly load the module.
    const query = eval("require('~/database/query')");

    const sql = "SELECT text from TODO;";
    const [ vars ] = await query(sql);

    return {
      vars,
    };
  },
};

function isNodejs() {
  return typeof window === "undefined";
}
~~~

Note that this works only because `renderToHtml: true`: when `renderToHtml: true`, Goldpage calls `addInitialProps` on the server. (You can see that the result of `addInitialProps` is serialized and added to the HTML of your page in order to make the data available in the browser when your page is rendered to the DOM.)

Otherwise, if `renderToHtml: false`, then Goldpage calls `addInitialProps` in the browser and any attempt to `require('fs')` will inherently fail. In that case you'd need to use [Wildcard API](https://github.com/reframejs/wildcard-api). Let me know if you are not sure why &mdash; I'm happy to explain.

If you plan to always render your pages to HTML then you should be able to skip using Wildcard.

If it makes things easier for you, you can invite me to your private repo and then we can talk about the codebase directly.

Let me know when something's not clear.

**Comment by chriscalo** [comment]
Thanks for the explanation. I might give Wildcard API a try, that looks promising.

Here's what I'm trying to do. Do you see anywhere I'm going astray. Any recommend?

**Server-side render Vue components to HTML, passing in data from the file system / database.** I'm hoping to avoid building an API just to merge data into a Vue component. And I don't want to have to limit my options just to *universal* npm modules that can run in Node.js and in a browser. I'd really love if the logic in Goldpage `*.page.js` config files ran only on the server, not in the browser, making it possible to use modules like `fs` and `mysql-promise`.

**Rehydrate the Vue component HTML once it reaches the browser.** I'm loving that Goldpage handles this for me. I don't want to give up rich client-side interaction to get the benefits of server-side rendering. Of course, I'll need to build an API for on-page interactivity that requires a server round trip, but that's not hard to do in Express.

**Keep all routing logic on the server.** I want to keep all of my routing logic the server, either in Express handlers or in Goldpage `*.page.js` config files. Every time a new URL is requested, there's a full page refresh. This means I don't have to write **universal** code that can run in Node.js or on the browser for each page refresh. Instead, I'd rather every page load be loaded entirely on the server. Down the road, I might consider something a little more sophisticated like what [inertia.js][] is doing with their mix of HTML and XHR responses.

Thoughts? How do I write non-universal code for fetching data from a database in Node.js and passing it to a SSR'd Vue component using Goldpage?

Thanks again.

[inertia.js]: https://inertiajs.com/how-it-works

**Comment by brillout** [comment]
> I'm hoping to avoid building an API just to merge data into a Vue component.

Yes that's a great idea, there is no need for GraphQL/REST when there is a 1:1 relationship between frontend and backend.


>  I'll need to build an API for on-page interactivity that requires a server round trip, but that's not hard to do in Express.

Yep exactly. You can then use Wildcard instead of creating Express routes yourself.

> Any recommendations on the approach?

That's a wonderful approach that I would also choose.

>  How do I write non-universal code for fetching data from a database in Node.js and passing it to a SSR'd Vue component using Goldpage?

You can do that by using the `eval` trick I mentioned earlier. But you're absolutely right, what you are describing should have first-class support; you shouldn't have to use the `eval` trick to achieve that. I'll have some thoughts about this. I'll come back to you once I found a user friendly solution. In the mean time you can use the `eval` trick (let me know if the `eval` trick is not clear to you and I'll show it to you in a PR to your Goldpage starter).

I'm curious; what it is you are building?

**Comment by chriscalo** [comment]
> A trick to bypass webpack is to use eval:

Is there not some way to specify Node.js as the target environment for the server-side Goldpage build? Something like [webpack-node-externals][]?

From their README:

---

In your webpack.config.js:

``` js
var nodeExternals = require('webpack-node-externals');
...
module.exports = {
    ...
    target: 'node', // in order to ignore built-in modules like path, fs, etc.
    externals: [nodeExternals()], // in order to ignore all modules in node_modules folder
    ...
};
```

And that's it. All node modules will no longer be bundled but will be left as require('module').

---

> I'm curious; what it is you are building?

Nothing too exciting: it’s an old PHP app a friend wrote that I’m modernizing to Node.js + Vue. Because it’s something we won’t spend a lot of time on going forward, I’m trying to really optimize for developer economics so it's easy to make changes. But I’m also using this project as an opportunity to build out some patterns I like (a simple Vue SSR + Express setup) so I can quickly scaffold future projects.

[webpack-node-externals]: https://www.npmjs.com/package/webpack-node-externals

**Comment by brillout** [comment]
Telling Webpack to ignore native node modules alleviates the problem only to a certain degree. Goldpage shouldn't add any server-side code to browser bundles.

Goldpage shouldn't add `import { query } from "~/util/db";` to the bundles that are being shipped to the browser.

I'm thinking about a solution. I'll keep you updated.

**Comment by chriscalo** [comment]
Ah, got it. I keep forgetting that the page config modules are entry points for both server and client bundles. Thanks for giving this some thought 👍

**Comment by brillout** [comment]
I made good progress this WE on how to solve this.

I don't know (yet) when I will finalize and implement the solution.

In the meantime I recommend using Wildcard. (Instead of using the `eval` trick.)

Using Goldpage with Wildcard will provide what you want. If it's not clear let me know and I will elaborate.

I opened a new ticket for it: #13.

**Comment by chriscalo** [comment]
Sounds great, I will try using Goldpage with Wildcard. If you have a working example that I can reference, let me know. I didn't find a wildcard example in [the Goldpage examples directory][goldpage-examples], and [the example in the Wildcard API repo][wildcard-api-example] doesn't appear to be using Goldpage. If not, no worries, I'll see how far I can can get.

[goldpage-examples]: https://github.com/reframejs/goldpage/tree/master/examples
[wildcard-api-example]: https://github.com/reframejs/wildcard-api/tree/master/example

**Comment by chriscalo** [comment]
I was able to find [reframe-full-stack][] repo. I'll start there.

[reframe-full-stack]: https://github.com/reframejs/reframe-full-stack

**Comment by brillout** [comment]
:+1: Let me know if you have questions. Happy to do some more PRs to your repos.

**Comment by chriscalo** [comment]
Just tried to add Wilcard API to my app, but getting `Error: only absolute urls are supported`.

`pages/index.page.js`:

``` js
import { endpoints } from "wildcard-api/client";
import index from "./index.vue";
import { route } from "~/util";

export default {
  route: route(__filename),
  view: index,
  async addInitialProps() {
    return {
      time: new Date(),
      greeting: await endpoints.greet(),
    };
  },
  renderToHtml: true,
};
```

`api/index.js`:

``` js
import { endpoints } from "wildcard-api";
import { file } from "ez-file";

endpoints.greet = async function greet() {
  return await file("./greeting.txt");
};
```

`api/greeting.txt`:

``` text
Hello, World!
```

The server seems to start fine, but when visiting the root URL, I get the following error:

``` text
{ Error: only absolute urls are supported
    at /Users/chriscalo/Projects/goldpage-vue-express-starter/node_modules/node-fetch/index.js:54:10
    at new Promise (<anonymous>)
    at new Fetch (/Users/chriscalo/Projects/goldpage-vue-express-starter/node_modules/node-fetch/index.js:49:9)
    at Fetch (/Users/chriscalo/Projects/goldpage-vue-express-starter/node_modules/node-fetch/index.js:37:10)
    at addHandli (/Users/chriscalo/Projects/goldpage-vue-express-starter/.build/nodejs/webpack:/node_modules/wildcard-api/client/makeHttpRequest.js:9:1)
    at /Users/chriscalo/Projects/goldpage-vue-express-starter/.build/nodejs/webpack:/node_modules/wildcard-api/client/makeHttpRequest.js:90:1
    at makeHttpRequest (/Users/chriscalo/Projects/goldpage-vue-express-starter/.build/nodejs/webpack:/node_modules/wildcard-api/client/makeHttpRequest.js:29:1)
    at callEndpointOverHttp (/Users/chriscalo/Projects/goldpage-vue-express-starter/.build/nodejs/webpack:/node_modules/wildcard-api/client/WildcardClient.js:80:1)
    at fetchEndpoint (/Users/chriscalo/Projects/goldpage-vue-express-starter/.build/nodejs/webpack:/node_modules/wildcard-api/client/WildcardClient.js:57:1)
    at Proxy.<anonymous> (/Users/chriscalo/Projects/goldpage-vue-express-starter/.build/nodejs/webpack:/node_modules/wildcard-api/client/WildcardClient.js:226:1)

    at Object.greet [as addInitialProps] (/Users/chriscalo/Projects/goldpage-vue-express-starter/.build/nodejs/webpack:/pages/index.page.js:11:33)
    at retrieveInitialProps (/Users/chriscalo/Projects/goldpage-vue-express-starter/node_modules/@brillout/repage/common/getInitialProps.js:55:22)
    at getInitialProps (/Users/chriscalo/Projects/goldpage-vue-express-starter/node_modules/@brillout/repage/common/getInitialProps.js:21:41)
    at renderPageHtml (/Users/chriscalo/Projects/goldpage-vue-express-starter/node_modules/@brillout/repage/common/renderPageHtml.js:10:36)
    at getPageHtml (/Users/chriscalo/Projects/goldpage-vue-express-starter/node_modules/@brillout/repage/getPageHtml.js:25:24)
    at getHtml (/Users/chriscalo/Projects/goldpage-vue-express-starter/node_modules/@goldpage/server-universal-middleware/ServerRendering.js:62:24) isNetworkError: tru
e, isServerError: null, response: null }
```

**Comment by chriscalo** [comment]
Things are getting closer with Wildcard API, and I'm loving the elegant programming model. I ran into an error when trying to access `this` in a wildcard endpoint function and filed an issue:

https://github.com/reframejs/wildcard-api/issues/16

**Comment by brillout** [comment]
> I don't think this was mentioned in the Wildcard API docs

It's purposely not mentioned in the docs.

The idea is to show proper error messages and normally you would have gotten an error like this:

~~~
    Endpoint `greet` doesn't exist.
    You didn't define any endpoint function.
    Did you load your endpoint definitions? E.g. `require('./path/to/your/endpoint-functions.js')`.
~~~

But I forgot to add this explanation as well for SSR. It's not fixed & published under `0.5.4`.

> I'm loving the elegant programming model

Glad to hear.

Btw thanks for pushing on `goldpage dev & nodemon ./path/to/server.js`. I like it a lot. It's lovely to have a user that pushes me to improve the design.

**Comment by chriscalo** [comment]
> Btw thanks for pushing on goldpage dev & nodemon ./path/to/server.js. I like it a lot. It's lovely to have a user that pushes me to improve the design.

It's so nice to hear that, thanks 🙏. For me, that change was definitely the moment Goldpage went from something with a lot of potential to a very compelling tool. I've tried every other method I could find for SSRing Vue components, and Goldpage is the only one that both works and isn't a convoluted mess. I think you're really onto something powerful here.

**Comment by brillout** [comment]
> isn't a convoluted mess

Yes, that was precisely my goal with Goldpage. To be do-one-thing-do-it-well whereas others are too framework-ish.

> I've tried every other method I could find for SSRing Vue components, and Goldpage is the only one that both works and isn't a convoluted mess. I think you're really onto something powerful here.

Hehe thanks. Could I use this quote in a future landing page?

**Comment by chriscalo** [comment]
> Could I use this quote in a future landing page?

Yes, feel free 👍
