### ISSUE TITLE
Goldpage assumes port 3218 is open for Autoreload

### ISSUE THREAD

**Issue by chriscalo** [reframejs/goldpage#8]
I have 2 instances of Goldpage running and got the following warning from `goldpage dev`:

``` text
****************************************
*************** Warning ****************
****************************************
Autoreload will not work.
Because the port 3218 is already in use.
```

I'm guessing port 3218 is hardcoded somewhere. Could it instead use the [`portfinder`](https://www.npmjs.com/package/portfinder) module to find a nearby available port?

``` js
// port might be 3218, 3219, 3220, etc
const port = await portfinder.getPortPromise({ port: 3218 });
```

**Comment by brillout** [comment]
Fixed & new Goldpage version `0.5.4` published.

Try again -- the error message will let you know how to solve your situation.

**Comment by brillout** [comment]
> I have 2 instances of Goldpage running

Why are you dev 2 web apps in parallel? Sounds like an exotic setup; makes me curious.

**Comment by brillout** [comment]
> Could it instead use the portfinder module to find a nearby available port?

Btw thanks for the proposed solution. I didn't know about `portfinder` which is neat module.

I went for another solution because the browser code needs to know about the port; the port needs to be determined at build-time but `portfinder` would determine the port at server-start-time.

**Comment by chriscalo** [comment]
You're fast 😉

In this situation, the apps aren't related, they're just running on the same machine at a the same time. I have my real app running + the [goldpage-vue-express-starter][]. I first try things out in the starter repo because there's less going on and it's in a known working state. Once I get something working in the starter repo, I try to repeat it in my real app.

I feel like users of goldpage shouldn't have to specify which port Autoreload runs on. (For a related problem, this is why I created [express-start][]: to never have to think about which port a server is running on. It just finds a port and tells me which one it found.)

> I went for another solution because the browser code needs to know about the port; the port needs to be determined at build-time but `portfinder` would determine the port at server-start-time.

Just saw this, I now understand why a static port is needed at build time. 👍

[goldpage-vue-express-starter]: https://github.com/chriscalo/goldpage-vue-express-starter
[express-start]: https://www.npmjs.com/package/express-start

**Comment by chriscalo** [comment]
Though, I wonder: could the Goldpage SSR handler inject something like the following into each HTML response? 🤔

``` html
<script>var AUTORELOAD_PORT = 3221;</script>
```

**Comment by brillout** [comment]
> Once I get something working in the starter repo, I try to repeat it in my real app.

Ok I see.

> I feel like users of goldpage shouldn't have to specify which port Autoreload runs on. 

Agreed. And it's theoretically possible to determine the port with `portfinder` at server-start-time and have the client dynamically retrieve the correct port. But it would complexify Goldpage's codebase so I decided against this. I expect the default auto-reload port number 3128 to work out for the vast majority of users.

> could the Goldpage SSR handler inject something like the following into each HTML response? thinking

That's not an option because when you set `renderHtmlAtBuildTime: true`, Goldpage generates the HTML of your page at build-time.

**Comment by chriscalo** [comment]
Got it, makes sense 👍
